### ISSUE TITLE
lacking a LICENSE

### ISSUE THREAD

**Issue by divinity76** [Znote/POTCP#10]
should really fix that, with an unclear license, people may avoid using it because the license is unclear, or avoid contributing because the license is unclear. 

open-source OT projects have traditionally been licensed under the `GNU GPL V2` (because the original OTServ project, as well as TheForgottenServer are both GPLv2), but i dislike that license myself.. for reasons. 
![](http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-strip.jpg)

my go-to license for `people can do whatever they want with this code` is `The Unlicense`: https://choosealicense.com/licenses/unlicense/ - it is basically like WTFPL without the swearing, and is so simple that even average humans (non-lawyers) can understand the license without issue:

> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 

(anyone with basic English can understand that license without issues, wouldn't you say?)

another license i like, if you want to **__force__** people to say `thanks` in their own program for using POTCP in their own programs, is the MIT license: https://choosealicense.com/licenses/mit/

- and if you're going for the GPL, i urge you to go to the LGPL instead of the GPL, it is a less invasive version of GPL (if you use GPL then every project using POTCP must also be licensed under the GPL, but if you use LGPL then projects that are using other licenses than GPL can also use POTCP - for example, if you license this under GPL, you cannot use it in ZnoteAAC because ZnoteAAC is not licensed under the GPL itself.)

- `The Unlicense` and `MIT` and `LGPL` are pretty much the only suggestions i've got. (and disclaimer: IANAL)

**Comment by Znote** [comment]
There we go. 👍 

Znote/POTCP is licensed under the
MIT License
A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
